config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :user_abouts
    resources :matches do
      resources :comments
    end
    get 'team/show'
    resources :team
    get 'user/profile'
    get 'match/show_stat'
    root 'matches#index'
    get 'match/filters'
    devise_for :users
    get 'user/edit_info'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user_about.rb
class UserAbout < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/controllers/user_abouts_controller.rb
# frozen_string_literal: true

# user_about controller
class UserAboutsController < ApplicationController
  before_action :set_user_about, only: %i[show edit update destroy]

  # GET /user_abouts or /user_abouts.json
  def index
    @user_abouts = UserAbout.all
  end

  # GET /user_abouts/1 or /user_abouts/1.json
  def show; end

  # GET /user_abouts/new
  def new
    @user_about = UserAbout.new
  end

  # GET /user_abouts/1/edit
  def edit; end

  # POST /user_abouts or /user_abouts.json
  def create
    @user_about = UserAbout.new(user_about_params)

    respond_to do |format|
      if @user_about.save
        format.html { redirect_to user_about_url(@user_about), notice: 'User about was successfully created.' }
        format.json { render :show, status: :created, location: @user_about }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_abouts/1 or /user_abouts/1.json
  def update
    respond_to do |format|
      if @user_about.update(user_about_params)
        format.html { redirect_to root_path, notice: 'User about was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_abouts/1 or /user_abouts/1.json
  def destroy
    @user_about.destroy

    respond_to do |format|
      format.html { redirect_to user_abouts_url, notice: 'User about was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_about
    @user_about = UserAbout.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_about_params
    params.require(:user_about).permit(:fav_club, :image)
  end
end

app/helpers/user_abouts_helper.rb
module UserAboutsHelper
end

app/views/user_abouts/_form.html.erb
<%= form_with(model: user_about, url: user_about_path(locale, current_user.id), method: :patch) do |form| %>
  <% if user_about.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_about.errors.count, "error") %> prohibited this user_about from being saved:</h2>

      <ul>
        <% user_about.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field mb-3">
        
        <% teams = Team.all %>
        <% teams_name = {} %>
        <% teams[1...20].each do |team| %>
          <% teams_name[team[:team_name]] = team[:id] %>
        <% end %>

        <%= form.select(:fav_club, ["#{t('team')}", *teams_name]) %>
    </div>

    <div class="field mb-3">
      <%= form.label "#{t('picture')}", class: 'login_text form-label' %><br /> 
      <%= form.file_field :image, class: 'add_image_url' %>
    </div>

    <div class="actions">
      <%= form.submit "#{t('update')}", class: 'btn btn-primary' %>
    </div> 
<% end %>
</div>

app/views/user_abouts/_user_about.html.erb
<div id="<%= dom_id user_about %>">
  <p>
    <strong>User:</strong>
    <%= user_about.user_id %>
  </p>

  <p>
    <strong>Fav club:</strong>
    <%= user_about.fav_club %>
  </p>

  <p>
    <strong>Comments:</strong>
    <%= user_about.comments %>
  </p>

</div>

app/views/user_abouts/edit.html.erb
<%= stylesheet_link_tag "signup.css" %>
<div class='login_form container'>
  <h2 class='login_text'><%= "#{t('fav_club')}"%></h2>

  <%= render "form", user_about: @user_about %>

</div>

app/views/user_abouts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User abouts</h1>

<div id="user_abouts">
  <% @user_abouts.each do |user_about| %>
    <%= render user_about %>
    <p>
      <%= link_to "Show this user about", user_about %>
    </p>
  <% end %>
</div>

<%= link_to "New user about", new_user_about_path %>

app/views/user_abouts/new.html.erb
<h1>New user about</h1>

<%= render "form", user_about: @user_about %>

<br>

<div>
  <%= link_to "Back to user abouts", user_abouts_path %>
</div>

app/views/user_abouts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_about %>

<div>
  <%= link_to "Edit this user about", edit_user_about_path(@user_about) %> |
  <%= link_to "Back to user abouts", user_abouts_path %>

  <%= button_to "Destroy this user about", @user_about, method: :delete %>
</div>