config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resources :user_abouts
    resources :matches do
      resources :comments
    end
    get 'team/show'
    resources :team
    get 'user/profile'
    get 'match/show_stat'
    root 'matches#index'
    get 'match/filters'
    devise_for :users
    get 'user/edit_info'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/match.rb
class Match < ApplicationRecord
    has_many :teams
    has_many :comments
end

app/controllers/match_controller.rb
# frozen_string_literal: true

# match controller
class MatchController < ApplicationController
  def show_all
    @db = Match.all
    @teams = Team.all
    @teams_name = {}
    @teams.each do |team|
      @teams_name[team[:team_name]] = team[:id]
    end
  end

  # def show_stat
  #   @match = Match.find(params[:id])
  #   @match_stat = @match[:statistic].split(', ')
  #   @sop1 = Team.find(@match[:sop1_id])
  #   @sop2 = Team.find(@match[:sop2_id])
  #   @vlad = @match_stat[0].split
  #   @udar_v_stvor = @match_stat[1].split
  #   @udar_mimo = @match_stat[2].split
  #   @ugol_udar = @match_stat[3].split
  #   @shtraf_udar = @match_stat[4].split
  # end

  def filters
    @teams = Team.all
    @team_id = params[:team]
    @team_name = Team.find(@team_id)[:team_name] if @team_id
    @years = params[:year]
    @league = params[:league]
    @place = params[:place]
    @need_matches = Match
    right_year if @years
    right_league if @league
    if @place == 'home'
      search_home
    else
      search_guest
    end
    @array = @need_matches.count
  end

  private

  def right_year
    @year = @years.split('-')
    @year[0] = "#{@year[0]}-01-01"
    @year[1] = "#{@year[1]}-01-01"
  end

  def right_league
    leg = @league.split
    @leag = ''
    leg.each do |word|
      @leag += word[0]
    end
  end

  def search_home
    @need_matches = @need_matches.where(sop1_id: @team_id) if @team_id
    search
  end

  def search_guest
    @need_matches = @need_matches.where(sop2_id: @team_id) if @team_id
    search
  end

  def search
    @need_matches = @need_matches.where(match_date: @year[0]..@year[2]) if @years
    @need_matches = @need_matches.where(style: @leag) if @league
  end
end

app/controllers/matches_controller.rb
# frozen_string_literal: true

# match controller
class MatchesController < ApplicationController
  before_action :set_match, only: %i[show edit update destroy]

  # GET /matches or /matches.json
  def index
    @db = Match.all
    @teams = Team.all
    @teams_name = {}
    @teams.each do |team|
      @teams_name[team[:team_name]] = team[:id]
    end
  end

  # GET /matches/1 or /matches/1.json
  def show
    @match = Match.find(params[:id])
    @match_stat = @match[:statistic].split(', ')
    @sop1 = Team.find(@match[:sop1_id])
    @sop2 = Team.find(@match[:sop2_id])
    @vlad = @match_stat[0].split
    @udar_v_stvor = @match_stat[1].split
    @udar_mimo = @match_stat[2].split
    @ugol_udar = @match_stat[3].split
    @shtraf_udar = @match_stat[4].split
  end

  def new
    @match = Match.new
  end

  def edit; end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to match_url(@match), notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to match_url(@match), notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def filters
  #   @teams = Team.all
  #   @team_id = params[:team]
  #   @team_id = 1 if @team_id
  #   @team_name = Team.find(@team_id)[:team_name] if @team_id
  #   @years = params[:year]
  #   @league = params[:league]
  #   @place = params[:place]
  #   @need_matches = Match.all
  #   right_year if @years
  #   right_league if @league
  #   if @place == 'home'
  #     search_home
  #   else
  #     search_guest
  #   end
  # end

  private

  def right_year
    @year = @years.split('-')
    @year[0] = "#{@year[0]}-01-01"
    @year[1] = "#{@year[1]}-01-01"
  end

  def right_league
    leg = @league.split
    @leag = ''
    leg.each do |word|
      @leag += word[0]
    end
  end

  def search_home
    @need_matches = @need_matches.where(sop1_id: @team_id) if @team_id
    search
  end

  def search_guest
    @need_matches = @need_matches.where(sop2_id: @team_id) if @team_id
    search
  end

  def search
    @need_matches = @need_matches.where(match_date: @year[0]..@year[1]) if @years
    @need_matches = @need_matches.where(style: @leag) if @league
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_match
    @match = Match.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def match_params
    params.require(:match).permit(:sop, :schet, :shotout, :style, :statistic)
  end
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sop, style: "display: block" %>
    <%= form.text_field :sop %>
  </div>

  <div>
    <%= form.label :schet, style: "display: block" %>
    <%= form.text_field :schet %>
  </div>

  <div>
    <%= form.label :shotout, style: "display: block" %>
    <%= form.check_box :shotout %>
  </div>

  <div>
    <%= form.label :style, style: "display: block" %>
    <%= form.text_field :style %>
  </div>

  <div>
    <%= form.label :statistic, style: "display: block" %>
    <%= form.text_field :statistic %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/_match.html.erb
<div id="<%= dom_id match %>">
  <p>
    <strong>Sop:</strong>
    <%= match.sop %>
  </p>

  <p>
    <strong>Schet:</strong>
    <%= match.schet %>
  </p>

  <p>
    <strong>Shotout:</strong>
    <%= match.shotout %>
  </p>

  <p>
    <strong>Style:</strong>
    <%= match.style %>
  </p>

  <p>
    <strong>Statistic:</strong>
    <%= match.statistic %>
  </p>

</div>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Show this match", @match %> |
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/index.html.erb
<h1><%="#{t('matches')}"%></h1>

<%= stylesheet_link_tag "show_match.css" %>

<div class="filters">
  <%= form_tag("/match/filters", :method => :get) do %>
    <select name="team">
      <option value='' disabled selected><%="#{t('team')}"%></option>
      <%= options_for_select(@teams_name)%>
    </select>
    <select name="year">
      <option value="" disabled selected><%="#{t('season')}"%></option>
      <option value='2018-2019'>18/19</option>
      <option value='2019-2020'>19/20</option>
      <option value='2020-2021'>20/21</option>
      <option value='2021-2022'>21/22</option>
      <option value='2022-2023'>22/23</option>
    </select>
    <select name="league">
      <option value='' disabled selected><%="#{t('league')}"%></option>
      <option value='Бауманская Футбольная Лига'><%="#{t('league_b')}"%></option>
      <option value='Измайловская Футбольная Лига'><%="#{t('league_i')}"%></option>
    </select>
    <select name="place">
      <option value='home'><%="#{t('place_home')}"%></option>
      <option value='guest'><%="#{t('place_guest')}"%></option>
    </select>
    <%= submit_tag( "#{t('search')}", class: 'btn btn-success') %>
  <% end %>
</div>

<div class='today_matches'>
<% @db.each do |zap| %>
  <% id = zap.id %>
  <div class='one_match' id='<%= zap.id %>'>
    <p class='sop'><%= @teams.find(zap[:sop1_id])[:team_name] %> - <%= @teams.find(zap[:sop2_id])[:team_name] %></p>
    <p class='style'><%= zap.style %></p>
    <p class='schet'><%= "#{t('schet')}" %>: <%= zap.schet%></p>
    <p class='date'><%= "#{t('date')}" %>: <%= zap.match_date %></p>
    <button><%= link_to "#{t('statistic')}", match_path(locale, id), method: :get, id: 'stat_button', :style=>'color: black; text-decoration: none' %></button>
  </div>
<% end %>
</div>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/show.html.erb
<%= stylesheet_link_tag "show_stat.css" %>
<%= stylesheet_link_tag "comments.css" %>

<div class='match container-sm'>
  <div class='statistic'>
    <div class='sop'>
      <span class='sop'><%= link_to @sop1[:team_name], team_path(locale, @sop1) %>  <%= link_to @sop2[:team_name], team_path(locale, @sop2) %></span>
    </div>
  </div>
  <div class='statistic'>
    <div class='schet'>
      <p class='text-center st'><%= "#{t('schet')}" %> <%= @match[:schet]%></p>
    </div>
  </div>
  <div class='statistic'>
    <p class='text-center st_title'><%= "#{t('statistic')}" %> </p>
    <p class='text-center'><%= "#{t('possession')}" %> </p>
    <span class='statik'><%= @vlad[0] %><span>
    <span class='statik'><%= @vlad[1] %><span>
  </div>
  <div class='statistic'>
    <p class='text-center'><%= "#{t('udar_v_stvor')}" %></p>
    <span class='statik'><%= @udar_v_stvor[0] %><span>
    <span class='statik'><%= @udar_v_stvor[1] %><span>
  </div>
  <div class='statistic'>
    <p class='text-center'><%= "#{t('udar_mimo')}" %></p>
    <span class='statik'><%= @udar_mimo[0] %><span>
    <span class='statik'><%= @udar_mimo[0] %><span>
  </div>
  <div class='statistic'>
    <p class='text-center'><%= "#{t('ugol_udar')}" %></p>
    <span class='statik'><%= @ugol_udar[0] %><span>
    <span class='statik'><%= @ugol_udar[1] %><span>
  </div>
  <div class='statistic'>
    <p class='text-center'><%= "#{t('shtraf_udar')}" %></p>
    <span class='statik'><%= @shtraf_udar[0] %><span>
    <span class='statik'><%= @shtraf_udar[1] %><span>
  </div>
  <%= button_to "#{t('exit')}", root_path, class: "back_to_all btn btn-outline-primary", method: :get %>
</div>